backend:
  name: git-gateway
  branch: revamp
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title of the Page', name: 'title', widget: 'string' }
          - {
              label: 'Description of the Page',
              name: 'description',
              widget: 'string',
            }
          - {
              label: 'Headline',
              name: 'headline',
              widget: 'object',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'Subtitle', name: 'subtitle', widget: 'string' },
                ],
            }

  - name: 'projects'
    label: 'Projects'
    folder: 'src/pages/projects'
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Description', name: 'description', widget: 'string'}
      - {label: 'Featured Image', name: 'featuredImage', widget: 'image'}
      - {label: 'Technologies Used', name: 'technologies', widget: 'list', min: 1}
      - {label: 'Links', name: 'links', widget: 'list', min: 1}
      - {label: 'Text', name: 'body', widget: 'markdown'}